services:
  vigilia:
    restart: always
    container_name: vigilia
    image: louislam/uptime-kuma:1

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

        reservations:
          cpus: "0.1"
          memory: 256M

    ports:
      - 3001

    volumes:
      - vigilia:/app/data

volumes:
  vigilia:
    external: true
