services:
  vigilia:
    build: .
    restart: always

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

        reservations:
          cpus: "0.1"
          memory: 128M

    ports:
      - 3001

    volumes:
      - vigilia:/app/data

volumes:
  vigilia:
    external: true
